version: '3.1'
services:
  phoenix:
    build: .
    volumes:
      - .:/srv
    env_file:
      - envs/postgres
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - envs/postgres
volumes:
  postgres:
